# This dockerfile is used when drone builds the image.
from python:3.6-alpine

run apk add -U \
	ca-certificates \
 && rm -rf /var/cache/apk/*

add requirements.txt .
add wheeldir /wheeldir
run pip install --use-wheel --no-index --find-links=/wheeldir -r requirements.txt
run rm -rf /wheeldir /requirements.txt
add run_devpi.py /usr/bin/

entrypoint ["python3", "/usr/bin/run_devpi.py"]
